import type { Invoice } from "@/types";

export const DEMO_DATA: Invoice[] = [
  { invoice_id: "D-001", vendor_name: "Ghost Vendor Ltd", invoice_amount: 950000, decision: "BLOCK", risk_score: 97, rule_flags: "Missing PO, Unknown Vendor, Overbilling", ml_risk_score: 88, rule_score: 95, behavior_score: 20, fraud_type: "Shell Vendor Fraud", alert_level: "CRITICAL", network_risk_score: 85, shared_bank_account: 1, created_at: "2024-01-15" },
  { invoice_id: "D-002", vendor_name: "Split Co A", invoice_amount: 48000, decision: "BLOCK", risk_score: 88, rule_flags: "Split Invoice Pattern, Invoice Burst", ml_risk_score: 75, rule_score: 80, behavior_score: 35, fraud_type: "Split Invoice Fraud", alert_level: "CRITICAL", network_risk_score: 72, shared_bank_account: 0, created_at: "2024-01-15" },
  { invoice_id: "D-003", vendor_name: "Split Co A", invoice_amount: 47500, decision: "BLOCK", risk_score: 86, rule_flags: "Split Invoice Pattern, Invoice Burst", ml_risk_score: 72, rule_score: 78, behavior_score: 35, fraud_type: "Split Invoice Fraud", alert_level: "CRITICAL", network_risk_score: 72, shared_bank_account: 0, created_at: "2024-01-15" },
  { invoice_id: "D-004", vendor_name: "Benchmark Corp", invoice_amount: 120000, decision: "REVIEW", risk_score: 62, rule_flags: "High Deviation, Overpriced vs Benchmark", ml_risk_score: 55, rule_score: 60, behavior_score: 10, fraud_type: "Overbilling Fraud", alert_level: "HIGH", network_risk_score: 30, shared_bank_account: 0, created_at: "2024-01-16" },
  { invoice_id: "D-005", vendor_name: "Legit Supplies", invoice_amount: 25000, decision: "APPROVE", risk_score: 18, rule_flags: "None", ml_risk_score: 20, rule_score: 10, behavior_score: 5, fraud_type: "Normal", alert_level: "LOW", network_risk_score: 5, shared_bank_account: 0, created_at: "2024-01-16" },
  { invoice_id: "D-006", vendor_name: "Phantom Services", invoice_amount: 320000, decision: "BLOCK", risk_score: 91, rule_flags: "Unknown Vendor, Rounded Amount, Weekend Invoice", ml_risk_score: 84, rule_score: 90, behavior_score: 45, fraud_type: "Shell Vendor Fraud", alert_level: "CRITICAL", network_risk_score: 78, shared_bank_account: 1, created_at: "2024-01-17" },
  { invoice_id: "D-007", vendor_name: "Duplicate Inc", invoice_amount: 75000, decision: "REVIEW", risk_score: 71, rule_flags: "Duplicate Pattern, Rapid Resubmission", ml_risk_score: 65, rule_score: 72, behavior_score: 25, fraud_type: "Duplicate Invoice Fraud", alert_level: "HIGH", network_risk_score: 40, shared_bank_account: 0, created_at: "2024-01-17" },
];
